### ISSUE TITLE
Accessibility statement freeukgen

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#131] opened 2016-10-26 08:05 UTC
link to "access for all" on front page of website

**Comment by DeniseColbert** [comment] 2016-10-26 09:54
Duplicate of #95? Or should we have separate stories for each statement?

**Comment by PatReynolds** [comment] 2016-12-12 12:05
For main Free UK Gen website (should refer to what we are doing for all websites).

**Comment by PatReynolds** [comment] 2016-12-12 12:05
Place link in Footer of main website.

**Comment by DeniseColbert** [comment] 2016-12-15 12:38
Draft done, if you could have a look and let me know what else needs adding

**Comment by PatReynolds** [comment] 2017-01-11 12:53
That's fine - please add to footer.

**Comment by DeniseColbert** [comment] 2017-01-11 13:12
Done

**Closed** 2017-01-16 09:57 UTC
Labels: in progress
