### ISSUE TITLE
Conversion tracking on FreeCEN landing page

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#442] opened 2017-07-20 11:31 UTC
Code sent to Bev 20/7

**Comment by MikeLi1** [comment] 2017-07-20 11:45
Could you please let me know what you do about this conversion tracking because I would like to know how to do it in the future?

**Comment by DeniseColbert** [comment] 2017-07-21 09:00
Bev's email to Denise:

I've uploaded the script in Mike's email to the server, you can do the button change yourself from craft admin, the new code is: 

<form action="http://freecen2.freecen.org.uk"><center><button name="button" type="submit" onclick="goog_report_conversion('http://freecen2.freecen.org.uk')" class="ladda-button" data-style="contract" data-color="purple" data-size="1" draa-spinner-color="#ffffff">
<span class="ladda-label" style="font-weight:bold">Search </span>
<span class="ladda-spinner"></span>
</button></center></form>

**Comment by DeniseColbert** [comment] 2017-07-21 09:01
Bev emailed button code- I'll send to Mike as he would like to be involved also

**Comment by DeniseColbert** [comment] 2017-07-25 08:40
Analytics added to search button and FC1 link, Mike to test code.

**Comment by MikeLi1** [comment] 2017-07-26 13:07
The google conversion tracking code was not installed correctly
![google tag assistant report of freecen page](https://user-images.githubusercontent.com/8467446/28620050-375ae69c-7203-11e7-80ed-e50df3cadeab.JPG)
The problem is that the script is not installed inside the body tags
![google tag assistant report of freecen page - 2](https://user-images.githubusercontent.com/8467446/28620078-55a6b48c-7203-11e7-9f54-c8099d8cb230.JPG)
By checking the source code I found out that the code was placed inside the <head> </head> instead of the <body ></body>
It needs to be placed above the closing </body > like it is shown in here with an arrow
![showing with arrow where to place the script tag above the closing body tag](https://user-images.githubusercontent.com/8467446/28622051-00370ddc-720b-11e7-93cc-3f1cfcd0ebde.JPG)

I include the part that needs to be placed above the </body>:


<script type="text/javascript">
  /* <![CDATA[ */
  goog_snippet_vars = function() {
    var w = window;
    w.google_conversion_id = 930845010;
    w.google_conversion_label = "aLyCCMfMinMQ0qLuuwM";
    w.google_remarketing_only = false;
  }
  // DO NOT CHANGE THE CODE BELOW.
  goog_report_conversion = function(url) {
    goog_snippet_vars();
    window.google_conversion_format = "3";
    var opt = new Object();
    opt.onload_callback = function() {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  }
  var conv_handler = window['google_trackConversion'];
  if (typeof(conv_handler) == 'function') {
    conv_handler(opt);
  }
}
/* ]]> */
</script>
<script type="text/javascript"
  src="//www.googleadservices.com/pagead/conversion_async.js">
</script>

**Comment by DeniseColbert** [comment] 2017-07-26 13:09
@bev-fc could you take a look please?

**Comment by MikeLi1** [comment] 2017-07-26 13:10
I include the part that needs to be placed above the </body> and removed from inside the <head></head>:


<script type="text/javascript">
  /* <![CDATA[ */
  goog_snippet_vars = function() {
    var w = window;
    w.google_conversion_id = 930845010;
    w.google_conversion_label = "aLyCCMfMinMQ0qLuuwM";
    w.google_remarketing_only = false;
  }
  // DO NOT CHANGE THE CODE BELOW.
  goog_report_conversion = function(url) {
    goog_snippet_vars();
    window.google_conversion_format = "3";
    var opt = new Object();
    opt.onload_callback = function() {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  }
  var conv_handler = window['google_trackConversion'];
  if (typeof(conv_handler) == 'function') {
    conv_handler(opt);
  }
}
/* ]]> */
</script>
<script type="text/javascript"
  src="//www.googleadservices.com/pagead/conversion_async.js">
</script>

**Comment by DeniseColbert** [comment] 2017-07-26 13:16
Mike, I think there are some words missing?

"inside the instead of the " above screenshot 3
and "above the and removed from inside the :" below screenshot 3 and in your last comment

**Comment by MikeLi1** [comment] 2017-07-26 13:24
The part that needs to be placed above the closing body tag and be removed from inside the head tags

**Comment by bev-fc** [comment] 2017-07-26 14:07
@DeniseColbert  @MikeLi1 My bad. I have modified the script, please verify again.

**Comment by MikeLi1** [comment] 2017-07-26 14:23
Thanks @bev-fc . It seems to be installed properly now

![success](https://user-images.githubusercontent.com/8467446/28625876-6dc75758-7215-11e7-86b8-746e9ff8341f.JPG)

**Comment by DeniseColbert** [comment] 2017-07-26 14:28
Great work A - Team! (A = analytics)

**Closed** 2017-09-07 08:41 UTC
Labels: Adwords, FreeCEN
